#!/bin/sh
TIMER=0
SELECT=0
QUALITY=5
COPY_SS=0
SAVE_SS=0
NAME_SS="$(date '+%Y%m%d-%H%M%S').png"
SAVE_SS_DIR="$HOME/pics"

while getopts :scxt:q:n:p: flag; do
    case "${flag}" in
        t) TIMER=${OPTARG};;
        s) SELECT=1;;
        c) COPY_SS=1;;
        x) SAVE_SS=1;;
        q) QUALITY=${OPTARG};;
        n) NAME_SS=${OPTARG};;
        p) SAVE_SS_DIR=${OPTARG};;
        *) echo "usage: $0 [-xsc] [-t time(s)] [-q quality(1-10)] [-n name.png] [-p path/to/picture]"; exit 2 ;;
    esac
done

[ $SAVE_SS -eq 0 ] && [ $COPY_SS -eq 0 ] && COPY_SS=1
[ $SAVE_SS -eq 1 ] && [ ! -d "${SAVE_SS_DIR}" ] && mkdir -p "${SAVE_SS_DIR}"
[ $SELECT -eq 1 ] && TAGS="-s"

sleep "$TIMER"

maim $TAGS -m "$QUALITY" "${SAVE_SS_DIR}/${NAME_SS}" || exit 2

if [ $SAVE_SS -eq 1 ] && [ $COPY_SS -eq 1 ]; then
    xclip -selection clipboard -target image/png -i "${SAVE_SS_DIR}/${NAME_SS}"
    SHOW="$(echo "${SAVE_SS_DIR}" | sed -e "s|${HOME}|~|g")/${NAME_SS} (+CLIPBOARD)"
elif [ $SAVE_SS -eq 0 ] && [ $COPY_SS -eq 1 ]; then
    rm "${SAVE_SS_DIR}/${NAME_SS}"
    SHOW="CLIPBOARD"
elif [ $SAVE_SS -eq 1 ] && [ $COPY_SS -eq 0 ]; then
    SHOW="$(echo "${SAVE_SS_DIR}" | sed -e "s|${HOME}|~|g")/${NAME_SS}"
fi

dunstify -h string:x-dunst-stack-tag:screenshot -i "camera-on" \
    " Picture acquired!" "Saved in\n<span size='small'><u>${SHOW}</u></span>"