#!/bin/bash

# Get the current volume
current_volume=$(amixer get Master | awk 'flag==1{exit} /%/ {print $5; flag=1}' | tr -d '[]')

# Get the action from the first argument
action="$1"

# Get the amount from the second argument, if provided
amount="${low:-5}"

# Check if a notification id exists
if [ -f /tmp/volume_notification_id ]; then
	notification_id=$(cat /tmp/volume_notification_id)
else
	notification_id=""
fi

case "$action" in
"-u")
	# Increase the volume by the given amount
	amixer set Master "${amount}%+"
	if amixer get Master | grep -q "\[off\]"; then
		notification_id=$(dunstify -u low -t 3000 'Volume increased' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	else
		notification_id=$(dunstify -u low -t 3000 'Volume increased' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	fi
	;;
"-d")
	# Decrease the volume by the given amount
	amixer set Master "${amount}%-"
	if amixer get Master | grep -q "\[off\]"; then
		notification_id=$(dunstify -u low -t 3000 'Volume decreased' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	else
		notification_id=$(dunstify -u low -t 3000 'Volume decreased' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	fi
	;;
"-s")
	# Set the volume to the given value
	amixer set Master "${amount}%"
	if amixer get Master | grep -q "\[off\]"; then
		notification_id=$(dunstify -u low -t 3000 'Volume set' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	else
		notification_id=$(dunstify -u low -t 3000 'Volume set' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	fi
	;;
"-t")
	# Toggle mute/unmute
	amixer set Master toggle >/dev/null && sleep 0.1
	if amixer get Master | grep -q "\[off\]"; then
		notification_id=$(dunstify -u low -t 3000 'Volume muted' 'Your system volume is now muted')
		echo "$notification_id" >/tmp/volume_notification_id
	else
		notification_id=$(dunstify -u low -t 3000 'Volume unmuted' "Your system volume changed to $current_volume%")
		echo "$notification_id" >/tmp/volume_notification_id
	fi
	;;
*)
	echo "Usage: volume_controller.sh [-u | -d | -s | -t] [amount]"
	echo "-u: Increase volume by [amount] (default: 5)"
	echo "-d: Decrease volume by [amount] (default: 5)"
	echo "-s: Set volume to [amount]"
	echo "-t: Toggle mute/unmute"
	;;
esac
